# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0002_parking_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
