# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0003_parking_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='size',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='M', max_length=1),
        ),
    ]
