# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0004_parking_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='book_for',
            field=models.CharField(choices=[('D', 'Disabled'), ('DFLT', 'Default'), ('E', 'Electric')], default='DFLT', max_length=4),
        ),
    ]
