# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0006_parking_vehicule_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parking',
            old_name='vehicule_type',
            new_name='vehicle_type',
        ),
    ]
