# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0007_auto_20170311_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='book_for',
            field=models.CharField(choices=[('Disabled', 'Disabled'), ('Default', 'Default'), ('Electric', 'Electric')], default='Default', max_length=8),
        ),
        migrations.AlterField(
            model_name='parking',
            name='is_free',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parking',
            name='is_paying',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parking',
            name='size',
            field=models.CharField(choices=[('Small', 'Small'), ('Medium', 'Medium'), ('Large', 'Large')], default='Medium', max_length=6),
        ),
        migrations.AlterField(
            model_name='parking',
            name='vehicle_type',
            field=models.CharField(choices=[('Car', 'Car'), ('MotoCycle', 'MotoCycle'), ('Truck', 'Truck')], default='Car', max_length=9),
        ),
    ]
