# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0008_auto_20170311_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='book_for',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='parking',
            name='size',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterField(
            model_name='parking',
            name='vehicle_type',
            field=models.CharField(max_length=9),
        ),
    ]
