# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 21:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0009_auto_20170311_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='book_for',
            field=models.CharField(default='Default', max_length=8),
        ),
        migrations.AlterField(
            model_name='parking',
            name='size',
            field=models.CharField(default='Medium', max_length=6),
        ),
        migrations.AlterField(
            model_name='parking',
            name='vehicle_type',
            field=models.CharField(default='Car', max_length=9),
        ),
    ]
