# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0010_auto_20170311_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='frequency',
            field=models.CommaSeparatedIntegerField(default=2, max_length=7),
            preserve_default=False,
        ),
    ]
