# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-11 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parking', '0011_parking_frequency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parking',
            name='count',
        ),
        migrations.AlterField(
            model_name='parking',
            name='frequency',
            field=models.CommaSeparatedIntegerField(default='0,0,0,0,0,0,0', max_length=7),
        ),
    ]
